site_name: Projet-cyna
nav: 
  - Home: index.md
  - Bonnes-pratiques: about.md
  - DevSecOps: devsecops.md
  - Gitlab: gitlab.md
  - WorkflowGit: workflowgit.md
theme:
  name: mkdocs
  color_mode: dark 
