site_name: Projet-cyna
nav: 
  - Home: index.md
  - Bonnes-pratiques: about.md
  - DevSecOps: devsecops.md
  - Gitlab: gitlab.md
  - WorkflowGit: workflowgit.md
theme: jekyll-theme-minimal
  color_mode: dark
  
