site_name: Projet-cyna
nav: 
  - Home: index.md
  - Bonnes-pratiques: about.md
  - DevSecOps: devsecops.md
  - Gitlab: gitlab.md
  - WorkflowGit: workflowgit.md
  - Kubernetes: kubernetes.md
  - Grafana/Prometeus: gra-pro.md
  - ElasticSearch: elastic.md

theme:
  name: material
 
